# Generated by Django 4.2.7 on 2023-11-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'admin_table',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_symbol', models.CharField(max_length=10, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('market_capitalization', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dividend_yield', models.DecimalField(decimal_places=2, max_digits=5)),
                ('beta', models.DecimalField(decimal_places=2, max_digits=6)),
                ('week_52_high', models.DecimalField(decimal_places=2, max_digits=10)),
                ('week_52_low', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'stock_table',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(default='kalyan', max_length=128)),
                ('date_of_birth', models.DateField()),
                ('mobile_number', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'user_table',
            },
        ),
    ]
